### ISSUE TITLE
Feature request: Simple controller driver

### ISSUE THREAD

**Issue by r57zone** [terminal29/Simple-OpenVR-Driver-Tutorial#1]
Hello, It would be nice to see a self simple driver for controllers (like valve HMD ["driver sample"](https://github.com/ValveSoftware/openvr/tree/master/samples/driver_sample) ) for DIY VR Controllers. 

As an example, can change the position, rotation and buttons using the keyboard buttons. [I did the same](https://github.com/r57zone/OpenVR-head-tracking-with-buttons/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L358) for "driver_sample".

For DIY HMD there are few OpenVR drivers ([FreeTrack & OpenTrack](https://github.com/r57zone/OpenVR-OpenTrack) or [Arduino or simple api](https://github.com/TrueOpenVR/TrueOpenVR-Core)).

Thanks.

**Comment by terminal29** [comment]
I have a work in progress controller driver for OSVR (here)[https://github.com/terminal29/OSVR-SteamVR-Bridge] that I used as a substitute for the official SteamVR OSVR driver. Bear in mind the thread in the constructor was a bit of a hack because putting the osvr functions in RunFrame was causing unknown issues. As for your question I don't really understand what you're asking sorry.

**Comment by r57zone** [comment]
My feature request the sample code driver openvr for vr controllers (without OSVR).

**Comment by terminal29** [comment]
Sorry for the delay, I will release the completed driver + source when I have finished the tutorial.

**Comment by terminal29** [comment]
I've just released the final driver with HMD and controller support + uploaded the code. I'm going to close this now but feel free to reopen if you have any issues.

**Comment by r57zone** [comment]
Thanks
